#!/usr/bin/env python
"""Merge the no_loo ablation results into the existing five-variant results and
regenerate the ranking tables + dot heatmap with six arms.

Stages a merged tree under ablation_noloo/merged/ that has the same layout the
aggregators expect, then runs aggregate_{covid,mo,health_aging}.py and
grand_combine.py against it with ABL_DIR / ABL_VARIANTS pointing at the merged
tree. Nothing under the original ablation directory is read-write; it is only
read.

Layouts differ per family and are handled separately:
  covid       Metric rows x "{variant}-{size}" columns  -> outer join on Metric
  multiomics  Metric rows x "{variant}" columns         -> outer join on Metric
  health_aging  no summary is stored; the aggregator builds it from
                <root>/<variant>/{P1,P2,P3,G1}.json     -> copy the JSON dirs
"""
import os, shutil, subprocess, sys, glob
import pandas as pd

ORIG = "/dcs07/hongkai/data/harry/result/ablation"
NEW = "/dcs07/hongkai/data/harry/result/ablation_noloo"
MERGED = os.path.join(NEW, "merged")
HERE = os.path.dirname(os.path.abspath(__file__))
VARIANTS = ["proportion_only", "rmd_only", "no_batch_removal",
            "linear_regression", "original", "no_loo"]
TESTS = ["P1", "P2", "P3", "G1"]
missing = []


def join_summary(rel):
    """Copy ORIG/rel, outer-joining the no_loo columns from NEW/rel onto Metric."""
    src, extra, dst = os.path.join(ORIG, rel), os.path.join(NEW, rel), os.path.join(MERGED, rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    # dtype=str: the original columns are copied through verbatim (a float round-trip
    # would perturb the last ULP of e.g. Spearman_pval), and read_csv parses them back.
    base = pd.read_csv(src, index_col=0, dtype=str)
    if os.path.exists(extra):
        add = pd.read_csv(extra, index_col=0, dtype=str)
        order = list(base.index) + [i for i in add.index if i not in base.index]
        base = base.join(add, how="outer").reindex(order)
        print(f"  {rel}: {base.shape[0]} metrics x {base.shape[1]} cols (+{add.shape[1]}: {list(add.columns)})")
    else:
        missing.append(rel)
        print(f"  MISSING no_loo for {rel}")
    base.to_csv(dst, index_label="Metric")


def main():
    print("== staging merged tree ==")
    # aggregate_covid.py globs ablation_summary_covid_*.csv, which would re-read its own
    # ALL output from a previous run and collide on column names.
    stale = os.path.join(MERGED, "covid", "ablation_summary_covid_ALL.csv")
    if os.path.exists(stale):
        os.remove(stale)
    for f in sorted(glob.glob(os.path.join(ORIG, "covid", "ablation_summary_covid_*.csv"))):
        if f.endswith("_ALL.csv"):      # regenerated by aggregate_covid.py; not an input
            continue
        join_summary(os.path.relpath(f, ORIG))
    for f in sorted(glob.glob(os.path.join(ORIG, "multiomics", "*", "ablation_summary_mo_*.csv"))):
        join_summary(os.path.relpath(f, ORIG))
    for v in VARIANTS:
        srcdir = os.path.join(NEW if v == "no_loo" else ORIG, "health_aging", v)
        dstdir = os.path.join(MERGED, "health_aging", v)
        os.makedirs(dstdir, exist_ok=True)
        got = []
        for t in TESTS:
            p = os.path.join(srcdir, f"{t}.json")
            if os.path.exists(p):
                shutil.copy2(p, os.path.join(dstdir, f"{t}.json")); got.append(t)
        if not got:
            missing.append(f"health_aging/{v}")
        print(f"  health_aging/{v}: {got or 'MISSING'}")

    env = dict(os.environ, ABL_DIR=MERGED, ABL_VARIANTS=",".join(VARIANTS))
    steps = [("aggregate_covid.py", []), ("aggregate_mo.py", []),
             ("aggregate_health_aging.py", []), ("grand_combine.py", []),
             ("make_score_heatmaps.py", []),
             # the manuscript's Supplementary Fig. 4 is the five-dataset version
             ("make_score_heatmaps.py",
              ["--exclude", "health_aging", "--suffix", "_no_health_aging"])]
    for script, args in steps:
        print(f"\n===== {script} {' '.join(args)} =====")
        subprocess.run([sys.executable, os.path.join(HERE, script)] + args, env=env, check=True)

    if missing:
        print("\n!! no_loo results MISSING for:", missing)
    else:
        print("\nAll datasets have a no_loo arm.")
    print("Outputs under", MERGED)


if __name__ == "__main__":
    main()
