# ===== Harmony Preprocessing Parameters =====
h5ad_path: "/users/hjiang/GenoDistance/Data/count_data.h5ad"
sample_meta_path: "/users/hjiang/GenoDistance/Data/sample_data.csv"
output_dir: "/users/hjiang/GenoDistance/result"
sample_col: "sample"
grouping_columns:
  - "sev.level"
cell_column: "cell_type"
cell_meta_path: null
batch_col: 'batch'
markers: null
cluster_resolution: 0.92
num_PCs: 20
num_harmony: 30
num_features: 2000
min_cells: 500
min_features: 500
pct_mito_cutoff: 20
exclude_genes: null
doublet: true
combat: true
method: "average"
metric: "euclidean"
distance_mode: "centroid"
vars_to_regress: null
verbose: true

# ===== Cell Type Clustering Parameters =====
existing_cell_types: false
n_target_cell_clusters: 5
umap: true
cell_type_save: true

# ===== Cell Type Assignment Parameters =====
assign_save: true

# ===== Pseudobulk Parameters =====
sample_col: "sample"
celltype_col: "cell_type"
pseudobulk_output_dir: null
n_features: 2000
frac: 0.3
pseudobulk_verbose: true

# ===== PCA Parameters =====
n_expression_pcs: 10
n_proportion_pcs: 10
pca_output_dir: null
AnnData_sample_path: "/users/hjiang/GenoDistance/result/harmony/adata_sample.h5ad"
pca_verbose: true

# ===== Trajectory Analysis Parameters =====
trajectory_supervised: false
cca_output_dir: null
sev_col_cca: "sev.level"
cca_optimal_cell_resolution: false
cca_pvalue: true
trajectory_verbose: true
TSCAN_origin: null

# ===== Trajectory Differential Gene Parameters =====
fdr_threshold: 0.05
effect_size_threshold: 1
top_n_genes: 100
trajectory_diff_gene_covariate: null
num_splines: 5
spline_order: 3
trajectory_diff_gene_output_dir: null
visualization_gene_list: null
visualize_all_deg: True
top_n_heatmap: 50
trajectory_diff_gene_verbose: True
top_gene_number: 30

# ===== Paths for Skipping Preprocessing =====
AnnData_cell_path: "/users/hjiang/GenoDistance/result/harmony/adata_cell.h5ad"

# ===== Sample Distance Parameters =====
summary_sample_csv_path: null
sample_distance_methods: null

# ===== Cluster Based DEG ===== 
Kmeans_based_cluster_flag: true
Tree_building_method: null
proportion_test: false
RAISIN_analysis: true
cluster_distance_method: 'cosine'
cluster_number: 4
user_provided_sample_to_clade: null

# ===== Visualization Parameters =====
verbose_Visualization: true
trajectory_visualization_label: "sev.level"
age_bin_size: null
dot_size: 3

plot_dendrogram_flag: true
plot_cell_umap_by_plot_group_flag: true
plot_umap_by_cell_type_flag: true
plot_pca_2d_flag: false
plot_pca_3d_flag: false
plot_3d_cells_flag: false

plot_cell_type_proportions_pca_flag: false
plot_cell_type_expression_pca_flag: false
plot_pseudobulk_batch_test_expression_flag: false
plot_pseudobulk_batch_test_proportion_flag: false

# ===== ATAC-seq Pipeline Parameters =====
atac_preprocessing: true
atac_pseudobulk_dimensionality_reduction: true
atac_visualization_processing: true

atac_file_path: "/users/hjiang/GenoDistance/Data/ATAC.h5ad"
atac_output_dir: null
atac_metadata_path: "/users/hjiang/GenoDistance/Data/ATAC_Metadata.csv"
atac_pseudobulk_output_dir: null
atac_pca_output_dir: null
atac_sample_col: "sample"
atac_batch_col: null
atac_cell_type_column: "cell_type"
atac_pipeline_verbose: true
use_snapatac2_dimred: true
atac_min_cells: 3
atac_min_genes: 2000
atac_max_genes: 15000
atac_min_cells_per_sample : 500
atac_doublet: true
atac_tfidf_scale_factor: 10000
atac_num_features: 40000
atac_n_lsi_components: 30
atac_drop_first_lsi: true
atac_harmony_max_iter: 30
atac_n_neighbors: 15
atac_n_pcs: 30
atac_leiden_resolution: 0.8
atac_leiden_random_state: 42
atac_umap_min_dist: 0.3
atac_umap_spread: 1.0
atac_umap_random_state: 42
atac_plot_dpi: 300
atac_pseudobulk_n_features: 40000
atac_pseudobulk_frac: 0.1
atac_pseudobulk_verbose: true
atac_pca_n_expression_pcs: 30
atac_pca_n_proportion_pcs: 30
atac_pca_verbose: true
atac_figsize: [10, 8]  
atac_point_size: 50
atac_visualization_grouping_columns:
  - current_severity
  - Donor
atac_visualization_age_size: null

# ===== Process Control Flags =====
preprocessing: false
cell_type_cluster: false
sample_distance_calculation: false
DimensionalityReduction: false
trajectory_analysis: false
trajectory_differential_gene: false
cluster_and_DGE: false
ATAC_data: true
visualize_data: false
initialization: false
use_gpu: false
