# ========================================
# MAIN PIPELINE PARAMETERS
# ========================================
output_dir: "/dcs07/hongkai/data/harry/result/Benchmark"

# ========================================
# PIPELINE CONTROL FLAGS
# ========================================
# Overall pipeline control
run_rna_pipeline: false
run_atac_pipeline: false
run_multiomics_pipeline: true

# System configuration
use_gpu: true
initialization: false
verbose: true
save_intermediate: true

# ========================================
# RNA PIPELINE PARAMETERS
# ========================================
# Required RNA parameters
rna_count_data_path: "/dcl01/hongkai/data/data/hjiang/Data/paired/rna/all.h5ad"
rna_sample_meta_path: null
rna_output_dir: null

# RNA Process Control Flags
rna_preprocessing: false
rna_cell_type_cluster: true
rna_dimensionality_reduction: true
rna_sample_distance_calculation: false
rna_trajectory_analysis: false
rna_trajectory_dge: false
rna_sample_cluster: false
rna_cluster_dge: false
rna_visualize_data: false

# RNA Paths for Skipping Processes
rna_anndata_cell_path: "/dcl01/hongkai/data/data/hjiang/result/harmony/adata_cell.h5ad"
rna_anndata_sample_path: "/dcl01/hongkai/data/data/hjiang/result/harmony/adata_sample.h5ad"
rna_pseudobulk_adata_path: null

# RNA Basic Parameters
rna_sample_col: "sample"
rna_grouping_columns: 
  - "sev.level"
rna_cell_type_column: "cell_type"
rna_cell_meta_path: null
rna_batch_col: null
rna_markers: null
rna_cluster_resolution: 0.6
rna_num_pcs: 20
rna_num_harmony: 30
rna_num_features: 2000
rna_min_cells: 500
rna_min_features: 500
rna_pct_mito_cutoff: 20
rna_exclude_genes: null
rna_doublet: true
rna_method: "average"
rna_metric: "euclidean"
rna_distance_mode: "centroid"
rna_vars_to_regress: null

# RNA Cell Type Clustering Parameters
rna_existing_cell_types: false
rna_n_target_cell_clusters: null
rna_umap: true
rna_assign_save: true

# RNA Cell Type Annotation Parameters
rna_cell_type_annotation: false
rna_cell_type_annotation_model_name: null
rna_cell_type_annotation_custom_model_path: null

# RNA Pseudobulk Parameters
rna_celltype_col: "cell_type"
rna_pseudobulk_output_dir: "/dcl01/hongkai/data/data/hjiang/result/pseudobulk"
rna_pseudobulk_n_features: 2000
rna_pseudobulk_verbose: true

# RNA PCA Parameters
rna_n_expression_components: 10
rna_n_proportion_components: 10
rna_harmony_for_proportion: true
rna_dr_output_dir: null
rna_dr_verbose: true

# RNA Trajectory Analysis Parameters
rna_trajectory_supervised: true
rna_n_components_for_cca: 2
rna_cca_output_dir: null
rna_sev_col_cca: "sev.level"
rna_cca_optimal_cell_resolution: true
rna_cca_pvalue: false
rna_trajectory_verbose: true
rna_tscan_origin: null

# RNA Trajectory Differential Gene Parameters
rna_fdr_threshold: 0.05
rna_effect_size_threshold: 1
rna_top_n_genes: 100
rna_trajectory_diff_gene_covariate: null
rna_num_splines: 5
rna_spline_order: 3
rna_trajectory_diff_gene_output_dir: null
rna_visualization_gene_list: null
rna_visualize_all_deg: true
rna_top_n_heatmap: 50
rna_trajectory_diff_gene_verbose: true
rna_n_pcs_for_null: 10

# RNA Distance Methods
rna_summary_sample_csv_path: null
rna_sample_distance_methods: 
  - "cosine"
  - "correlation"

# RNA Visualization Parameters
rna_verbose_visualization: true
rna_trajectory_visualization_label: 
  - "sev.level"
rna_age_bin_size: null
rna_age_column: "age"
rna_dot_size: 3
rna_plot_dendrogram_flag: true
rna_plot_umap_by_cell_type_flag: true
rna_plot_cell_type_proportions_pca_flag: false
rna_plot_cell_type_expression_umap_flag: false

# RNA Cluster Based DEG
rna_kmeans_based_cluster_flag: true
rna_tree_building_method: 
  - "HRA_VEC"
  - "HRC_VEC"
  - "NN"
  - "UPGMA"
rna_proportion_test: false
rna_raisin_analysis: true
rna_cluster_distance_method: "cosine"
rna_cluster_number: 4
rna_user_provided_sample_to_clade: null

# ========================================
# ATAC PIPELINE PARAMETERS
# ========================================
# Required ATAC parameters
atac_count_data_path: "/dcl01/hongkai/data/data/hjiang/Data/ATAC.h5ad"
atac_output_dir: null
atac_metadata_path: "/dcl01/hongkai/data/data/hjiang/Data/ATAC_Metadata.csv"

# ATAC Process Control Flags
atac_preprocessing: false
atac_cell_type_cluster: false
atac_pseudobulk_dimensionality_reduction: false
atac_visualization_processing: false
atac_trajectory_analysis: false
atac_sample_distance_calculation: false
atac_sample_cluster: false
atac_cluster_dge: false
atac_trajectory_dge: false

# ATAC Paths for Skipping Processes
atac_cell_path: null
atac_sample_path: null
atac_pseudobulk_adata_path: null

# ATAC Column specifications
atac_sample_col: "sample"
atac_batch_col: 'tissue'
atac_cell_type_column: "cell_type"
atac_grouping_columns:
  - "sev.level"
  - "Donor"

# ATAC Pipeline configuration
atac_pipeline_verbose: true
use_snapatac2_dimred: false

# ATAC QC and filtering parameters
atac_min_cells: 3
atac_min_genes: 2000
atac_max_genes: 15000
atac_min_cells_per_sample: 500

# ATAC Processing parameters
atac_doublet: true
atac_tfidf_scale_factor: 10000.0
atac_num_features: 40000
atac_n_lsi_components: 30
atac_drop_first_lsi: true
atac_harmony_max_iter: 30
atac_n_neighbors: 15
atac_n_pcs: 30

# ATAC Leiden clustering parameters
atac_leiden_resolution: 0.9
atac_existing_cell_types: false
atac_n_target_cell_clusters: null

# ATAC UMAP parameters
atac_umap_min_dist: 0.3
atac_umap_spread: 1.0
atac_umap_random_state: 42
atac_plot_dpi: 300

# ATAC Pseudobulk parameters
atac_pseudobulk_output_dir: null
atac_pseudobulk_n_features: 40000
atac_pseudobulk_verbose: true

# ATAC PCA parameters
atac_dr_output_dir: null
atac_dr_n_expression_components: 30
atac_dr_n_proportion_components: 30
atac_harmony_for_proportion: true
atac_dr_verbose: true

# ATAC Trajectory analysis parameters
atac_trajectory_supervised: true
atac_n_components_for_cca: 2
atac_cca_output_dir: null
atac_sev_col_cca: "sev.level"
atac_trajectory_verbose: true
atac_cca_pvalue: false
atac_cca_optimal_cell_resolution: true
atac_n_pcs_for_null: 10
atac_tscan_origin: null
atac_trajectory_visualization_label: 
  - "sev.level"

# ATAC Trajectory differential analysis parameters
atac_fdr_threshold: 0.05
atac_effect_size_threshold: 1
atac_top_n_genes: 100
atac_trajectory_diff_gene_covariate: null
atac_num_splines: 5
atac_spline_order: 3
atac_visualization_gene_list: null
atac_visualize_all_deg: true
atac_top_n_heatmap: 50
atac_trajectory_diff_gene_verbose: true
atac_top_gene_number: 30
atac_trajectory_diff_gene_output_dir: null

# ATAC Sample distance parameters
atac_sample_distance_methods: 
  - "cosine"
  - "correlation"
atac_summary_sample_csv_path: null

# ATAC Clustering parameters
atac_kmeans_based_cluster_flag: false
atac_tree_building_method: 
  - "HRA_VEC"
  - "HRC_VEC"
  - "NN"
  - "UPGMA"
atac_proportion_test: false
atac_raisin_analysis: false
atac_cluster_distance_method: "cosine"
atac_cluster_number: 4
atac_user_provided_sample_to_clade: null

# ATAC Visualization parameters
atac_figsize: [10, 8]
atac_point_size: 50
atac_visualization_grouping_columns:
  - "sev.level"
  - "Donor"
atac_show_sample_names: true
atac_visualization_age_size: null
atac_age_bin_size: null
atac_verbose_visualization: true
atac_dot_size: 3
atac_plot_dendrogram_flag: true
atac_plot_cell_umap_by_plot_group_flag: true
atac_plot_umap_by_cell_type_flag: true
atac_plot_pca_2d_flag: true
atac_plot_pca_3d_flag: true
atac_plot_3d_cells_flag: true
atac_plot_cell_type_proportions_pca_flag: true
atac_plot_cell_type_expression_pca_flag: true
atac_plot_pseudobulk_batch_test_expression_flag: false
atac_plot_pseudobulk_batch_test_proportion_flag: false

# ========================================
# MULTIOMICS PIPELINE PARAMETERS
# ========================================
# Multiomics Required Parameters
multiomics_rna_file: '/dcl01/hongkai/data/data/hjiang/Data/paired/rna/all.h5ad'
multiomics_atac_file: "/dcl01/hongkai/data/data/hjiang/Data/paired/atac/all.h5ad"
multiomics_output_dir: null

# Multiomics Main Control Flags
multiomics_run_glue: true
multiomics_run_integrate_preprocess: true
multiomics_run_dimensionality_reduction: true
multiomics_run_visualize_embedding: true
multiomics_run_find_optimal_resolution: false

# Multiomics GLUE Sub-Step Control Flags
multiomics_run_glue_preprocessing: false
multiomics_run_glue_training: false
multiomics_run_glue_gene_activity: true
multiomics_run_glue_cell_types: true
multiomics_run_glue_visualization: false

# Multiomics Basic Parameters
multiomics_rna_sample_meta_file: null
multiomics_atac_sample_meta_file: null
multiomics_additional_hvg_file : '/dcl01/hongkai/data/data/hjiang/Data/multi_omics_testing/unique_genes.txt'
multiomics_rna_sample_column: "sample"
multiomics_atac_sample_column: "sample"
multiomics_sample_column: "sample"
multiomics_sample_col: "sample"
multiomics_batch_col: null
multiomics_celltype_col: "cell_type"
multiomics_verbose: true
multiomics_use_gpu: true
large_data_need_extra_memory: true
multiomics_random_state: 42

# Multiomics GLUE Integration Parameters
multiomics_ensembl_release: 98
multiomics_species: "homo_sapiens"
multiomics_use_highly_variable: true
multiomics_n_top_genes: 1500
multiomics_n_pca_comps: 50
multiomics_n_lsi_comps: 50
multiomics_lsi_n_iter: 15
multiomics_gtf_by: "gene_name"
multiomics_flavor: "seurat_v3"
multiomics_generate_umap: false
multiomics_compression: "gzip"
multiomics_metadata_sep: ","
multiomics_consistency_threshold: 0.05
treat_sample_as_batch: False
multiomics_save_prefix: "glue"
multiomics_k_neighbors: 20
multiomics_use_rep: "X_glue"
multiomics_metric: "cosine"
multiomics_existing_cell_types: false
multiomics_n_target_clusters: null
multiomics_cluster_resolution: 0.8
multiomics_use_rep_celltype: "X_glue"
multiomics_markers: null
multiomics_method: "average"
multiomics_metric_celltype: "euclidean"
multiomics_distance_mode: "centroid"
multiomics_generate_umap_celltype: true
multiomics_plot_columns: null

# Multiomics Integration Preprocessing Parameters
multiomics_integrate_output_dir: null
multiomics_min_cells_sample: 1
multiomics_min_cell_gene: 10
multiomics_min_features: 500
multiomics_pct_mito_cutoff: 20
multiomics_exclude_genes: null
multiomics_doublet: true

# Multiomics Combined Dimensionality Reduction Parameters
# Pseudobulk Parameters
multiomics_pseudobulk_output_dir: null
multiomics_save: true
multiomics_n_features: 2000
multiomics_normalize: true
multiomics_target_sum: 10000.0
multiomics_atac: false

# PCA Parameters
multiomics_pca_sample_col: "sample"
multiomics_n_expression_pcs: 10
multiomics_n_proportion_pcs: 10
multiomics_harmony_for_proportion: true
multiomics_pca_output_dir: null
multiomics_integrated_data: false
multiomics_not_save: false
multiomics_pca_atac: false
multiomics_use_snapatac2_dimred: false

# Multiomics Visualization Parameters
multiomics_modality_col: "modality"
multiomics_color_col: "modality"
multiomics_target_modality: "ATAC"
multiomics_expression_key: "X_DR_expression"
multiomics_proportion_key: "X_DR_proportion"
multiomics_figsize: [20, 8]
multiomics_point_size: 60
multiomics_alpha: 0.8
multiomics_colormap: "viridis"
multiomics_viz_output_dir: null
multiomics_show_sample_names: false
multiomics_force_data_type: null

# Multiomics Optimal Resolution Parameters
multiomics_optimization_target: "rna"
multiomics_dr_type: "expression"
multiomics_resolution_n_features: 40000
multiomics_sev_col: "sev.level"
multiomics_resolution_batch_col: null
multiomics_resolution_sample_col: "sample"
multiomics_resolution_modality_col: "modality"
multiomics_resolution_use_rep: "X_glue"
multiomics_num_dr_components: 30
multiomics_num_pcs: 20
multiomics_num_pvalue_simulations: 1000
multiomics_n_pcs: 2
multiomics_compute_pvalues: true
multiomics_visualize_embeddings: true
multiomics_resolution_output_dir: null

# Multiomics Paths for Skipping Steps
multiomics_integrated_h5ad_path: null
multiomics_pseudobulk_h5ad_path: null